githubConfigUrl: "https://github.com/edbzn/k8s-bare-metal-ci"
githubConfigSecret: arc-github-app-secret

minRunners: 0
maxRunners: 3

containerMode:
  type: "dind"

template:
  spec:
    runtimeClassName: kata-fc
    nodeSelector:
      node-role: isolated-ci
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
