apiVersion: v1
kind: Pod
metadata:
  name: kata-fc-test
spec:
  runtimeClassName: kata-fc
  containers:
    - name: test
      image: 192.168.122.200:5000/alpine-test:v1
      command: ["sh", "-c", "uname -a; cat /proc/cpuinfo | grep 'model name' | head -1; sleep 3600"]
